### ISSUE TITLE
Save Image does not work on Firefox 48.0

### ISSUE THREAD

**Issue by carrere** [skutac/InCHlib.js#16]
Hi,

The Save Button does not work properly on Firefox 48.0: "loading ..." appear but no image is produced.
Show Image works perfectly.

And both options works on Chrome.

Using jquery-3.1.0.min.js + inchlib-1.2.0.min.js + kinetic-v5.1.0.min.js

Sebastien

**Comment by skutac** [comment]
Thank you, Sebastien.

I've just fixed this issue in the dev version of InCHlib, so it will be OK in the next version. If you need to use that functionality now, please, use the dev version, which should be as stable as the 1.2.0 version. You would just need to use Konva.js instead of Kinetic.

Best,
Ctibor

**Comment by carrere** [comment]
Thanks
